version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kiaid
    volumes:
      - "./db_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    expose:
      - 5432

  cache:
    image: "redis:alpine"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-github-pipeline:latest
    container_name: python-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kiaid
      POSTGRES_HOST: db
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"
    volumes:
      - "./db_data:/var/lib/postgresql/data:rw"